# vim: filetype=zsh

# Local bin to path
[ -d "$HOME/.local/bin" ] && export PATH="$HOME/.local/bin:$PATH"

# XDG dirs
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"

# XDG paths
export R_LIBS_USER="$XDG_DATA_HOME/R"
export PASSWORD_STORE_DIR="$XDG_DATA_HOME/password-store"
export ATOM_HOME="$XDG_DATA_HOME/atom"
export GOPATH="$XDG_DATA_HOME/go"
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export WGETRC="$XDG_CONFIG_HOME/wget/wgetrc"
export JUPYTER_CONFIG_DIR="$XDG_CONFIG_HOME/jupyter"
export GTK2_RC_FILES="$XDG_CONFIG_HOME"/gtk-2.0/gtkrc
export ICEAUTHORITY="$XDG_CACHE_HOME/ICEauthority"
export RXVT_SOCKET="$XDG_RUNTIME_DIR/urxvtd"
export LESSHISTFILE="-"
export XINITRC="$XDG_CONFIG_HOME/xinitrc"

# Environment variables
export VISUAL="nvim"
export EDITOR="nvim"
export PAGER="less"
export TERMINAL="alacritty"
export SUDO_ASKPASS="$HOME/.local/bin/sudoaskpass-dmenu"
export GPG_TTY="$(tty)"
export PASSWORD_STORE_GENERATED_LENGTH=8
export PASSWORD_STORE_CHARACTER_SET="[:alnum:]"

# Go bin to path
[ -d "$GOPATH/bin" ] && export PATH="$PATH:$GOPATH/bin"
